(()=>{
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const taskKey='homeTasksV4',examKey='homeExamsV4';
function wait(fn,n=60){if(fn())return;if(n)setTimeout(()=>wait(fn,n-1),100)}
wait(()=>{const main=document.querySelector('.app-main-area'),dash=$('view-dashboard');if(!main||!dash||!window.studyAppShow)return false;
 if(!document.getElementById('astHomeBtn')){const b=document.createElement('button');b.id='astHomeBtn';b.className='ast-home-btn';b.textContent='⌂ Home';b.onclick=()=>window.studyAppShow('dashboard');main.insertBefore(b,main.firstChild);}
 const hero=dash.querySelector('.dash-hero');if(hero){const k=hero.querySelector('.dash-kicker');if(k)k.textContent='My study planner';const h=hero.querySelector('h2');if(h)h.textContent='Hello! What are we studying today?';const p=hero.querySelector('#dashMessage');if(p)p.textContent='Your tasks, exams, study tools, notes and AI Study Team are all in one place.';}
 if(!document.getElementById('astHomeStrip')){const s=document.createElement('div');s.id='astHomeStrip';s.className='ast-home-strip';s.innerHTML=`<section class="ast-home-card"><h3>Focus Tasks</h3><div id="astTasks"></div><button class="ast-home-link" id="astAddTask">+ Add task</button></section><section class="ast-home-card"><h3>Upcoming Exams</h3><div id="astExams"></div><button class="ast-home-link" id="astAddExam">+ Add exam</button></section>`;(document.getElementById('studyHomeActions')||hero)?.insertAdjacentElement('afterend',s);$('astAddTask').onclick=()=>{const title=prompt('Task name');if(!title)return;const date=prompt('Due date (YYYY-MM-DD), or leave blank')||'';const a=read(taskKey,[]);a.push({id:Date.now(),title,date,done:false});write(taskKey,a);renderHome()};$('astAddExam').onclick=()=>{const title=prompt('Exam name or subject');if(!title)return;const date=prompt('Exam date (YYYY-MM-DD)')||'';const a=read(examKey,[]);a.push({id:Date.now(),title,date});write(examKey,a);renderHome()};}
 renderHome();return true});
function renderHome(){const t=$('astTasks'),e=$('astExams');if(t){const a=read(taskKey,[]);t.innerHTML=a.length?a.slice(0,5).map(x=>`<div class="ast-row"><label><input type="checkbox" data-taskdone="${x.id}" ${x.done?'checked':''}> ${esc(x.title)}</label><small>${esc(x.date||'No date')}</small></div>`).join(''):'<div class="ast-empty">Nothing due. Enjoy it.</div>';t.querySelectorAll('[data-taskdone]').forEach(c=>c.onchange=()=>{const a=read(taskKey,[]),x=a.find(v=>v.id==c.dataset.taskdone);if(x)x.done=c.checked;write(taskKey,a);renderHome()})}if(e){const a=read(examKey,[]).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'));e.innerHTML=a.length?a.slice(0,5).map(x=>`<div class="ast-row"><b>${esc(x.title)}</b><small>${esc(x.date||'Date not set')}</small></div>`).join(''):'<div class="ast-empty">Nothing on the horizon.</div>'}}
// Upgrade existing private Notes without replacing its storage or save handlers.
wait(()=>{const view=$('view-mynotes'),cat=$('mnCategory'),title=$('mnTitle');if(!view||!cat||!title)return false;if(!document.getElementById('notesTopicFilter')){const panel=view.querySelector('.panel');const tools=document.createElement('div');tools.className='notes-topic-tools';tools.innerHTML=`<select id="notesTopicFilter"><option value="all">All topics</option></select><input id="notesSearch" placeholder="Search your notes…">`;panel.insertBefore(tools,panel.querySelector('.mn-form'));const topics=['Algebra','Number','Fractions & Percentages','Sets & Venn Diagrams','Statistics','Geometry & Angles','Trigonometry','Matrices','Consumer Arithmetic','Coordinate Geometry','Other'];const dl=$('mnCategoryList');if(dl)dl.innerHTML=topics.map(x=>`<option value="${esc(x)}"></option>`).join('');const f=$('notesTopicFilter');f.innerHTML='<option value="all">All topics</option>'+topics.map(x=>`<option>${esc(x)}</option>`).join('');f.onchange=filterNotes;$('notesSearch').oninput=filterNotes;new MutationObserver(filterNotes).observe($('mnList'),{childList:true,subtree:true});}filterNotes();return true});
function filterNotes(){const list=$('mnList');if(!list)return;const f=$('notesTopicFilter')?.value||'all',q=($('notesSearch')?.value||'').toLowerCase();[...list.children].forEach(n=>{const txt=n.textContent.toLowerCase();n.style.display=(f==='all'||txt.includes(f.toLowerCase()))&&(!q||txt.includes(q))?'':'none'})}
window.addEventListener('storage',renderHome);
})();