(() => {
  const $=id=>document.getElementById(id),KEY='mistakeBookV2';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}},save=a=>localStorage.setItem(KEY,JSON.stringify(a));
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function addMistake(subject,q,a,idx=0,source='practice'){const list=read(),key=subject+'|'+q,old=list.find(x=>x.key===key);if(old){old.count=(old.count||0)+1;old.last=Date.now();old.mastered=false;if(source==='test')old.source='test'}else list.unshift({key,subject,q,a,idx,count:1,last:Date.now(),mastered:false,source});save(list);render()}
  function render(){const listEl=$('mistakeList'),summary=$('mistakeSummary');if(!listEl||!summary)return;const list=read(),active=list.filter(m=>!m.mastered).length;summary.textContent=list.length?`${active} to review · ${list.length-active} mastered`:'Nothing here yet — mistakes you make in Practice or Test Mode will appear here.';listEl.innerHTML=list.length?list.map((m,i)=>`<div class="mistake-card ${m.mastered?'mastered':''}"><div class="mistake-top"><span>${esc(m.subject)}</span><small>missed ${m.count||1}×${m.source==='test'?' · Test Mode':''}</small></div><b>${esc(m.q)}</b><div class="mistake-answer"><strong>Answer:</strong> ${esc(m.a)}</div><div class="mistake-actions"><button data-v3retry="${i}">Retry</button><button data-v3master="${i}">${m.mastered?'Mark for review':'I understand this ✓'}</button></div></div>`).join(''):'<div class="ci-empty">No mistakes saved yet 🎉</div>';
    listEl.querySelectorAll('[data-v3master]').forEach(b=>b.onclick=()=>{const a=read(),m=a[+b.dataset.v3master];if(m){m.mastered=!m.mastered;save(a);render()}});
    listEl.querySelectorAll('[data-v3retry]').forEach(b=>b.onclick=()=>{const m=read()[+b.dataset.v3retry];if(!m)return;try{qQuickMode=false;qSubject=m.subject;const sel=$('qSubject');if(sel)sel.value=qSubject;const deck=qCurrentDeck();const found=deck.findIndex(x=>x.q===m.q);qIndex=found>=0?found:Math.max(0,m.idx||0);qRenderQuestion();window.studyAppShow?.('questions')}catch{window.studyAppShow?.('study')}});
  }
  function install(){const view=$('view-mistakes'),btn=$('testSubmit');if(!view||!btn||typeof qRecordAttempt!=='function'){setTimeout(install,120);return}
    const clear=$('clearMasteredMistakes');if(clear&&!clear.dataset.v3){const clean=clear.cloneNode(true);clean.dataset.v3='1';clear.replaceWith(clean);clean.onclick=()=>{save(read().filter(m=>!m.mastered));render()}}
    qRecordAttempt=function(subject,correct){if(!qAttempts[subject])qAttempts[subject]={right:0,wrong:0};qAttempts[subject][correct?'right':'wrong']++;if(!correct){const item=qCurrentDeck()[qIndex];if(item)addMistake(item.subject||subject,item.q,item.a,item.idx||qIndex,'practice')}else if(typeof window.addStudyRewardPoints==='function')window.addStudyRewardPoints(2);gSave()};
    if(!btn.dataset.mistakeSync){btn.dataset.mistakeSync='1';btn.addEventListener('click',()=>setTimeout(()=>{const f=($('testFeedback')?.textContent||'').trim();if(!/^(?:not quite\.\s*)?answer:/i.test(f))return;const q=$('testQ')?.textContent||'',answer=f.replace(/^(?:not quite\.\s*)?answer:\s*/i,''),topic=$('testTopic')?.value||'Test Mode';if(q&&answer)addMistake(topic,q,answer,0,'test')},20))}
    new MutationObserver(()=>{if(view.classList.contains('active'))render()}).observe(view,{attributes:true,attributeFilter:['class']});render();
  }
  install();
})();