(() => {
  const $=id=>document.getElementById(id), KEY='plannerTasksV3', VIEW='plannerViewV3';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}, save=x=>localStorage.setItem(KEY,JSON.stringify(x));
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const fmt=d=>new Date(d+'T00:00:00').toLocaleDateString(undefined,{month:'long',day:'numeric'}).toUpperCase();
  const iso=d=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
  let month=new Date();month.setDate(1);let selected=iso(new Date());
  const wait=(n=40)=>{const v=$('view-planner');if(!v){if(n)setTimeout(()=>wait(n-1),100);return}if($('plannerV3'))return;mount(v)};wait();
  function generated(){try{return buildSchedule().map(x=>({id:'gen:'+iso(x.date),date:iso(x.date),topic:(x.topics||[]).map(t=>t[1]).slice(0,2).join(' • ')||'Book work',task:`Pages ${x.startPage}–${x.endPage}`,generated:true,exam:!!x.hasExam,done:x.endPage<=pagesDoneUpTo}))}catch{return[]}}
  function mount(view){const box=document.createElement('div');box.id='plannerV3';box.className='panel planner-v3';box.innerHTML=`<div class="suite-title"><div><h2>Planner</h2><p>Switch between a clean list and a monthly calendar. Your original book schedule stays below.</p></div></div><div class="planner-view-toggle"><button data-pview="list">List View</button><button data-pview="calendar">Calendar View</button></div><div class="planner-v3-add"><input type="date" id="pv3Date"><input id="pv3Topic" placeholder="Subject / topic"><input id="pv3Task" placeholder="Study task"><button class="fc-btn" id="pv3Add">Add task</button></div><div id="pv3List"></div><div id="pv3Calendar" style="display:none"></div>`;view.insertBefore(box,view.firstChild);$('pv3Date').value=selected;$('pv3Add').onclick=add;box.querySelectorAll('[data-pview]').forEach(b=>b.onclick=()=>setView(b.dataset.pview));setView(localStorage.getItem(VIEW)||'list')}
  function setView(v){localStorage.setItem(VIEW,v);document.querySelectorAll('[data-pview]').forEach(b=>b.classList.toggle('active',b.dataset.pview===v));$('pv3List').style.display=v==='list'?'block':'none';$('pv3Calendar').style.display=v==='calendar'?'block':'none';render()}
  function add(){const date=$('pv3Date').value,topic=$('pv3Topic').value.trim(),task=$('pv3Task').value.trim();if(!date||!topic||!task)return;const a=read();a.push({id:crypto.randomUUID(),date,topic,task,done:false});save(a);$('pv3Topic').value='';$('pv3Task').value='';selected=date;render()}
  function render(){renderList();renderCalendar()}
  function renderList(){const rows=[...read(),...generated()].sort((a,b)=>a.date.localeCompare(b.date));const groups={};rows.forEach(r=>(groups[r.date]||=[]).push(r));$('pv3List').innerHTML=Object.keys(groups).length?Object.entries(groups).map(([date,items])=>`<div class="planner-date-group"><div class="planner-date-title">${fmt(date)}</div>${items.map(r=>`<div class="planner-task-row ${r.done?'planner-complete':''} ${r.generated?'planner-generated':''}"><div><b>${esc(r.topic)}</b><small>${esc(r.task)}${r.exam?' · Exam':''}${r.generated?' · Book schedule':''}</small></div><div class="planner-task-actions">${r.generated?'':`<button data-toggle="${r.id}">${r.done?'↺':'✓'}</button><button data-edit="${r.id}">Edit</button><button data-del="${r.id}">×</button>`}</div></div>`).join('')}</div>`).join(''):'<p class="muted">No planner tasks yet.</p>';bind()}
  function bind(){document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const a=read(),r=a.find(x=>x.id===b.dataset.toggle);if(r){r.done=!r.done;save(a);render()}});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{save(read().filter(x=>x.id!==b.dataset.del));render()});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const a=read(),r=a.find(x=>x.id===b.dataset.edit);if(!r)return;const t=prompt('Edit task',r.task);if(t===null)return;const s=prompt('Edit subject/topic',r.topic);if(s===null)return;r.task=t.trim()||r.task;r.topic=s.trim()||r.topic;save(a);render()})}
  function renderCalendar(){const holder=$('pv3Calendar');if(!holder)return;const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prevDays=new Date(y,m,0).getDate(),all=[...read(),...generated()],today=iso(new Date());let cells='';for(let i=0;i<42;i++){let d,muted=false;if(i<start){d=new Date(y,m-1,prevDays-start+i+1);muted=true}else if(i>=start+days){d=new Date(y,m+1,i-start-days+1);muted=true}else d=new Date(y,m,i-start+1);const key=iso(d),items=all.filter(x=>x.date===key),exam=items.some(x=>x.exam);cells+=`<button class="planner-day ${muted?'muted':''} ${key===today?'today':''} ${key===selected?'selected':''} ${items.length?'has-task':''} ${exam?'exam':''}" data-date="${key}"><span class="planner-day-num">${d.getDate()}</span><div class="planner-day-items">${items.slice(0,2).map(x=>esc(x.topic)).join('<br>')}</div></button>`}holder.innerHTML=`<div class="planner-calendar-head"><button id="pvPrev">←</button><h3>${month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h3><button id="pvNext">→</button></div><div class="planner-calendar"><div class="planner-dow">Mon</div><div class="planner-dow">Tue</div><div class="planner-dow">Wed</div><div class="planner-dow">Thu</div><div class="planner-dow">Fri</div><div class="planner-dow">Sat</div><div class="planner-dow">Sun</div>${cells}</div><div class="planner-selected-day" id="pvSelected"></div>`;$('pvPrev').onclick=()=>{month.setMonth(month.getMonth()-1);renderCalendar()};$('pvNext').onclick=()=>{month.setMonth(month.getMonth()+1);renderCalendar()};holder.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{selected=b.dataset.date;$('pv3Date').value=selected;const d=new Date(selected+'T00:00:00');month=new Date(d.getFullYear(),d.getMonth(),1);renderCalendar()});renderSelected(all)}
  function renderSelected(all){const items=all.filter(x=>x.date===selected);$('pvSelected').innerHTML=`<div class="planner-date-title">${fmt(selected)}</div>${items.length?items.map(x=>`<div class="planner-task-row ${x.done?'planner-complete':''}"><div><b>${esc(x.topic)}</b><small>${esc(x.task)}${x.exam?' · Exam':''}</small></div></div>`).join(''):'<p class="muted">No tasks yet. Use the form above to add one for this date.</p>'}`}
  window.addEventListener('storage',render);
})();