(()=>{
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const PROFILE_KEY='sp8:profiles', FRIEND_KEY='sp8:friends';
const rawRead=(k,d)=>{try{return JSON.parse(window.StudyAccounts?.rawGet?.(k)||'null')??d}catch{return d}};
const rawWrite=(k,v)=>{try{window.StudyAccounts?.rawSet?.(k,JSON.stringify(v));return true}catch{return false}};
const current=()=>window.StudyAccounts?.current?.()||null;
const idOf=a=>a?.id||'';
const defaults=a=>({id:a.id,username:a.username,displayName:a.username,bio:'',pfp:'',banner:'',updated:Date.now()});
function profiles(){const all=rawRead(PROFILE_KEY,{});for(const a of (window.StudyAccounts?.list?.()||[]))all[a.id]={...defaults(a),...(all[a.id]||{}),id:a.id,username:a.username};return all}
function saveProfile(p){const all=profiles();all[p.id]=p;return rawWrite(PROFILE_KEY,all)}
function links(){return rawRead(FRIEND_KEY,[])}
function isFriend(a,b){return links().some(x=>(x.a===a&&x.b===b)||(x.a===b&&x.b===a))}
function friendIds(id){return links().filter(x=>x.a===id||x.b===id).map(x=>x.a===id?x.b:x.a)}
function toggleFriend(a,b){if(!a||!b||a===b)return;let x=links();const i=x.findIndex(v=>(v.a===a&&v.b===b)||(v.a===b&&v.b===a));if(i>=0)x.splice(i,1);else x.push({a,b,created:Date.now()});rawWrite(FRIEND_KEY,x);renderProfile(activeProfile||a);renderFriends()}
function wait(fn,n=120){if(fn())return;if(n)setTimeout(()=>wait(fn,n-1),100)}
function shrink(file,max,q=.78){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{const im=new Image();im.onerror=reject;im.onload=()=>{const s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',q))};im.src=r.result};r.readAsDataURL(file)})}
let activeProfile='';
wait(()=>{
 const side=$('appSideNav'),main=document.querySelector('.app-main-area');if(!side||!main||!window.studyAppShow||!current())return false;
 if(!$('view-profile')){const v=document.createElement('div');v.id='view-profile';v.className='view';main.appendChild(v)}
 if(!$('view-friends')){const v=document.createElement('div');v.id='view-friends';v.className='view';main.appendChild(v)}
 if(!side.querySelector('[data-shellgo="profile"]')){
   const profile=document.createElement('button');profile.dataset.shellgo='profile';profile.className='sp8-profile-link';profile.textContent='Profile';profile.onclick=()=>showProfile(idOf(current()));
   const friends=document.createElement('button');friends.dataset.shellgo='friends';friends.className='sp8-friends-link';friends.textContent='Friends';friends.onclick=()=>showFriends();
   const blog=side.querySelector('[data-shellgo="blog"]');if(blog){blog.after(friends);blog.after(profile)}else{const extra=$('sp6Extra');side.insertBefore(profile,extra||null);profile.after(friends)}
 }
 buildViews();return true;
});
function buildViews(){renderProfile(idOf(current()));renderFriends()}
function showProfile(id){activeProfile=id;window.studyAppShow?.('profile');renderProfile(id);mark('profile')}
function showFriends(){window.studyAppShow?.('friends');renderFriends();mark('friends')}
function mark(name){document.querySelectorAll('#appSideNav button[data-shellgo]').forEach(b=>b.classList.toggle('active',b.dataset.shellgo===name))}
function renderProfile(id){const host=$('view-profile'),me=current();if(!host||!me)return;const p=profiles()[id]||defaults(me),own=id===me.id,friend=isFriend(me.id,id),count=friendIds(id).length;
 host.innerHTML=`<div class="sp8-page"><div class="sp8-profile-head"><span>PROFILE</span><button class="sp8-friends-pill" data-openfriends>Friends</button></div><section class="sp8-profile-card"><div class="sp8-banner" ${p.banner?`style="background-image:url('${p.banner}')"`:''}>${own?'<button class="sp8-banner-btn" data-edit>✎ Edit profile</button>':''}</div><div class="sp8-profile-body"><div class="sp8-avatar-wrap"><div class="sp8-avatar" ${p.pfp?`style="background-image:url('${p.pfp}')"`:''}>${p.pfp?'':esc((p.displayName||p.username||'?').slice(0,1).toUpperCase())}</div></div><div class="sp8-profile-actions">${own?'<button class="sp8-outline" data-edit>✎ EDIT PROFILE</button>':`<button class="sp8-friend-btn ${friend?'added':''}" data-friend="${esc(id)}">${friend?'✓ FRIENDS':'+ ADD FRIEND'}</button>`}</div><h1>${esc(p.displayName||p.username)}</h1><div class="sp8-handle">@${esc(p.username)}</div><p class="sp8-bio">${esc(p.bio|| (own?'Add a bio so your friends know a little about you.':'No bio yet.'))}</p><div class="sp8-count"><strong>${count}</strong> ${count===1?'friend':'friends'}</div></div></section><section class="sp8-mini"><div><span>STUDY FRIENDS</span><strong>${count}</strong></div><button data-openfriends>View friends →</button></section></div>`;
 host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(p));host.querySelector('[data-friend]')?.addEventListener('click',()=>toggleFriend(me.id,id));host.querySelectorAll('[data-openfriends]').forEach(b=>b.onclick=showFriends)
}
function openEditor(p){if(p.id!==idOf(current()))return;const old=$('sp8EditModal');if(old)old.remove();const m=document.createElement('div');m.id='sp8EditModal';m.className='sp8-modal';m.innerHTML=`<div class="sp8-editor"><div class="sp8-editor-top"><h2>Edit profile</h2><button data-close>×</button></div><label>Display name<input id="sp8Name" maxlength="40" value="${esc(p.displayName||p.username)}"></label><label>Bio<textarea id="sp8Bio" maxlength="240" placeholder="Tell people about yourself...">${esc(p.bio||'')}</textarea></label><div class="sp8-upload-grid"><label class="sp8-upload">Profile photo<input id="sp8Pfp" type="file" accept="image/*" hidden><span>Choose image</span></label><label class="sp8-upload">Banner<input id="sp8Banner" type="file" accept="image/*" hidden><span>Choose image</span></label></div><div id="sp8EditMsg" class="sp8-msg"></div><button id="sp8Save" class="sp8-save">SAVE PROFILE</button></div>`;document.body.appendChild(m);let pfp=p.pfp,banner=p.banner;const msg=$('sp8EditMsg');m.querySelector('[data-close]').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};$('sp8Pfp').onchange=async()=>{const f=$('sp8Pfp').files?.[0];if(!f)return;msg.textContent='Preparing profile photo…';try{pfp=await shrink(f,500,.8);msg.textContent='Profile photo ready.'}catch{msg.textContent='Could not use that image.'}};$('sp8Banner').onchange=async()=>{const f=$('sp8Banner').files?.[0];if(!f)return;msg.textContent='Preparing banner…';try{banner=await shrink(f,1200,.76);msg.textContent='Banner ready.'}catch{msg.textContent='Could not use that image.'}};$('sp8Save').onclick=()=>{const displayName=$('sp8Name').value.trim()||p.username,bio=$('sp8Bio').value.trim();const next={...p,displayName,bio,pfp,banner,updated:Date.now()};if(!saveProfile(next)){msg.textContent='Could not save. Try a smaller image.';return}m.remove();renderProfile(p.id);renderFriends()}}
function renderFriends(){const host=$('view-friends'),me=current();if(!host||!me)return;const all=profiles(),ids=friendIds(me.id),others=Object.values(all).filter(p=>p.id!==me.id),friends=ids.map(id=>all[id]).filter(Boolean);host.innerHTML=`<div class="sp8-friends-page"><div class="sp8-friends-title"><div><span>COMMUNITY</span><h2>Friends.</h2><p>Find another Study account and add them to your study circle.</p></div><div class="sp8-friend-total">${friends.length}<small>friends</small></div></div><div class="sp8-search"><input id="sp8Search" placeholder="Search people by name or username..."></div><section><h3>Your friends</h3><div id="sp8FriendList" class="sp8-person-grid">${cards(friends,true)}</div></section><section><h3>Find people</h3><div id="sp8PeopleList" class="sp8-person-grid">${cards(others,false)}</div></section></div>`;wirePeople(host);$('sp8Search').oninput=()=>{const q=$('sp8Search').value.trim().toLowerCase(),list=others.filter(p=>!q||(p.displayName||'').toLowerCase().includes(q)||(p.username||'').toLowerCase().includes(q));$('sp8PeopleList').innerHTML=cards(list,false);wirePeople($('sp8PeopleList'))}}
function cards(list,friendSection){const me=current();if(!list.length)return `<div class="sp8-empty">${friendSection?'No friends added yet. Find someone below!':'No other accounts found yet.'}</div>`;return list.map(p=>{const f=isFriend(me.id,p.id);return `<article class="sp8-person"><button class="sp8-person-main" data-viewuser="${esc(p.id)}"><div class="sp8-person-avatar" ${p.pfp?`style="background-image:url('${p.pfp}')"`:''}>${p.pfp?'':esc((p.displayName||p.username||'?').slice(0,1).toUpperCase())}</div><div><strong>${esc(p.displayName||p.username)}</strong><span>@${esc(p.username)}</span><small>${esc((p.bio||'').slice(0,75))}</small></div></button><button class="sp8-small-friend ${f?'added':''}" data-togglefriend="${esc(p.id)}">${f?'Friends':'Add friend'}</button></article>`}).join('')}
function wirePeople(root){const me=current();root.querySelectorAll('[data-viewuser]').forEach(b=>b.onclick=()=>showProfile(b.dataset.viewuser));root.querySelectorAll('[data-togglefriend]').forEach(b=>b.onclick=()=>toggleFriend(me.id,b.dataset.togglefriend))}
window.addEventListener('storage',e=>{if(e.key===PROFILE_KEY||e.key===FRIEND_KEY){renderFriends();if(activeProfile)renderProfile(activeProfile)}});
})();