(()=>{
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const me=()=>window.StudyAccounts?.current?.()||null,sb=()=>window.StudyAccounts?.supabase?.();let active='';
function wait(fn,n=160){if(fn())return;if(n)setTimeout(()=>wait(fn,n-1),100)}
async function profile(id){const {data,error}=await sb().from('profiles').select('*').eq('id',id).single();if(error)throw error;return data}
async function counts(id){const [a,b]=await Promise.all([sb().from('follows').select('*',{count:'exact',head:true}).eq('following_id',id),sb().from('follows').select('*',{count:'exact',head:true}).eq('follower_id',id)]);return {followers:a.count||0,following:b.count||0}}
async function following(id){if(!me()||id===me().id)return false;const {data}=await sb().from('follows').select('follower_id').eq('follower_id',me().id).eq('following_id',id).maybeSingle();return !!data}
async function toggleFollow(id){if(!me()||id===me().id)return;const yes=await following(id);if(yes)await sb().from('follows').delete().eq('follower_id',me().id).eq('following_id',id);else await sb().from('follows').insert({follower_id:me().id,following_id:id});await render(id)}
function avatar(p,cls='sp8-avatar'){return p.avatar_url?`<img class="${cls}" src="${esc(p.avatar_url)}" alt="">`:`<div class="${cls} sp8-avatar-fallback">${esc((p.display_name||p.username||'?')[0].toUpperCase())}</div>`}
async function render(id){active=id;const v=$('view-profile');if(!v)return;v.innerHTML='<div class="sp8-loading">Loading profile…</div>';try{const p=await profile(id),c=await counts(id),own=id===me()?.id,isf=own?false:await following(id);v.innerHTML=`<section class="sp8-profile-card ${p.is_owner?'sp8-owner-profile':''}"><div class="sp8-banner" ${p.banner_url?`style="background-image:url('${esc(p.banner_url)}')"`:''}></div><div class="sp8-profile-body"><div class="sp8-avatar-wrap">${avatar(p,'sp8-profile-avatar')}</div><div class="sp8-profile-actions">${own?'<button class="sp8-pill" id="sp8Edit">Edit profile</button>':`<button class="sp8-pill sp8-primary" id="sp8Follow">${isf?'Following':'Follow'}</button>`}</div><h1>${esc(p.display_name)}</h1><div class="sp8-handle">@${esc(p.username)}</div><p class="sp8-bio">${esc(p.bio||'No bio yet.')}</p><div class="sp8-stats"><button data-list="followers"><b>${c.followers}</b> Followers</button><button data-list="following"><b>${c.following}</b> Following</button></div></div></section>`;v.querySelectorAll('[data-list]').forEach(b=>b.onclick=()=>showList(id,b.dataset.list,p));if(own)$('sp8Edit').onclick=()=>edit(p);else $('sp8Follow').onclick=()=>toggleFollow(id)}catch(e){v.innerHTML=`<div class="sp8-empty">Could not load this profile.</div>`}}
async function showList(id,type,p){let q=sb().from('follows').select(type==='followers'?'follower_id':'following_id').eq(type==='followers'?'following_id':'follower_id',id);const {data,error}=await q;if(error)return;const ids=(data||[]).map(x=>x[type==='followers'?'follower_id':'following_id']);let people=[];if(ids.length){const r=await sb().from('profiles').select('id,username,display_name,avatar_url').in('id',ids);people=r.data||[]}modal(`<div class="sp8-list-head"><div><span class="sp8-kicker">@${esc(p.username)}</span><h2>${type==='followers'?'Followers':'Following'}</h2></div><button class="sp8-x" data-close>×</button></div><div class="sp8-people">${people.length?people.map(x=>`<button class="sp8-person" data-person="${x.id}">${avatar(x,'sp8-mini-avatar')}<span><b>${esc(x.display_name)}</b><small>@${esc(x.username)}</small></span></button>`).join(''):'<div class="sp8-empty">Nobody here yet.</div>'}</div>`);document.querySelectorAll('[data-person]').forEach(x=>x.onclick=()=>{close();window.studyAppShow('profile');render(x.dataset.person)})}
function modal(html){close();const o=document.createElement('div');o.id='sp8Modal';o.className='sp8-modal';o.innerHTML=`<div class="sp8-modal-card">${html}</div>`;document.body.appendChild(o);o.onclick=e=>{if(e.target===o||e.target.closest('[data-close]'))close()}}
function close(){$('sp8Modal')?.remove()}
async function upload(file,kind){const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'jpg'),path=`${me().id}/${kind}-${Date.now()}.${ext}`;const {error}=await sb().storage.from('profile-media').upload(path,file,{upsert:true});if(error)throw error;return sb().storage.from('profile-media').getPublicUrl(path).data.publicUrl}
function edit(p){const canGif=(me()?.username||'').toLowerCase()==='mishkadotcom',imgAccept=canGif?'image/*':'image/jpeg,image/png,image/webp';modal(`<div class="sp8-list-head"><div><span class="sp8-kicker">Account</span><h2>Edit profile</h2></div><button class="sp8-x" data-close>×</button></div><form id="sp8EditForm" class="sp8-edit-form"><label>Display name<input id="sp8Display" maxlength="40" value="${esc(p.display_name)}" required></label><label>Bio<textarea id="sp8Bio" maxlength="240">${esc(p.bio||'')}</textarea></label><label>Profile picture<input id="sp8Pfp" type="file" accept="${imgAccept}"></label><label>Banner<input id="sp8Banner" type="file" accept="${imgAccept}"></label><button class="sp8-pill sp8-primary" type="submit">Save changes</button><div id="sp8EditMsg"></div></form>`);$('sp8EditForm').onsubmit=async e=>{e.preventDefault();const msg=$('sp8EditMsg');msg.textContent='Saving…';try{let avatar_url=p.avatar_url,banner_url=p.banner_url;if($('sp8Pfp').files[0])avatar_url=await upload($('sp8Pfp').files[0],'avatar');if($('sp8Banner').files[0])banner_url=await upload($('sp8Banner').files[0],'banner');const {error}=await sb().from('profiles').update({display_name:$('sp8Display').value.trim(),bio:$('sp8Bio').value.trim(),avatar_url,banner_url}).eq('id',me().id);if(error)throw error;close();await render(me().id)}catch(err){msg.textContent=err.message||'Could not save.'}}}
async function searchPeople(){modal(`<div class="sp8-list-head"><div><span class="sp8-kicker">Accounts</span><h2>Find people</h2></div><button class="sp8-x" data-close>×</button></div><input id="sp8SearchInput" class="sp8-search" placeholder="Search username or name"><div id="sp8SearchResults" class="sp8-people"></div>`);const input=$('sp8SearchInput'),out=$('sp8SearchResults');const go=async()=>{const term=input.value.trim();if(!term){out.innerHTML='<div class="sp8-empty">Type a name to search.</div>';return}const {data}=await sb().from('profiles').select('id,username,display_name,avatar_url').or(`username.ilike.%${term.replace(/[%_,()]/g,'')}%,display_name.ilike.%${term.replace(/[%_,()]/g,'')}%`).limit(20);out.innerHTML=(data||[]).map(x=>`<button class="sp8-person" data-person="${x.id}">${avatar(x,'sp8-mini-avatar')}<span><b>${esc(x.display_name)}</b><small>@${esc(x.username)}</small></span></button>`).join('')||'<div class="sp8-empty">No accounts found.</div>';out.querySelectorAll('[data-person]').forEach(x=>x.onclick=()=>{close();window.studyAppShow('profile');render(x.dataset.person)})};input.oninput=()=>{clearTimeout(input._t);input._t=setTimeout(go,250)};go()}
wait(()=>{const side=$('appSideNav'),main=document.querySelector('.app-main-area');if(!side||!main||!window.studyAppShow||!me()||!sb())return false;side.querySelectorAll('[data-view="friends"], .sp8-friends-nav').forEach(x=>x.remove());if(!$('view-profile')){const v=document.createElement('div');v.id='view-profile';v.className='view';main.appendChild(v)}let btn=side.querySelector('[data-view="profile"]');if(!btn){btn=document.createElement('button');btn.className='side-link';btn.dataset.view='profile';btn.innerHTML='<span>♡</span><span>Profile</span>';side.appendChild(btn)}btn.onclick=()=>{window.studyAppShow('profile');render(me().id)};let find=side.querySelector('#sp8FindPeople');if(!find){find=document.createElement('button');find.id='sp8FindPeople';find.className='side-link sp8-find-nav';find.innerHTML='<span>⌕</span><span>Find people</span>';side.appendChild(find)}find.onclick=searchPeople;const old=window.studyAppShow;window.studyAppShow=name=>{old(name);if(name==='profile')render(active||me().id)};render(me().id);return true});
window.StudySocial={renderProfile:render,findPeople:searchPeople};
})();