export default async function handler(req, res) {
  if (req.method !== 'POST') { res.setHeader('Allow','POST'); return res.status(405).json({error:'Method not allowed'}); }
  const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)return res.status(500).json({error:'OPENAI_API_KEY is not configured in Vercel.'});
  const body=req.body||{},validAgents=['manager','researcher','questionwriter','solver','verifier','tutor','mistakes','planner','examiner','flashcards','review','progress','goaltracker','studycoach','notes','challenge','syllabustracker','resourcefinder'];
  const agent=validAgents.includes(body.agent)?body.agent:'manager',mode=['teach','hint','check','practice'].includes(body.mode)?body.mode:'teach',topic=typeof body.topic==='string'?body.topic.slice(0,100):'auto';
  const messages=(Array.isArray(body.messages)?body.messages:[]).slice(-16).filter(m=>m&&['user','assistant'].includes(m.role)&&typeof m.content==='string').map(m=>({role:m.role,content:m.content.slice(0,3000)}));
  const r=body.studyContext&&typeof body.studyContext==='object'?body.studyContext:{};const studyContext={pagesDoneUpTo:r.pagesDoneUpTo??null,pagesPerDay:r.pagesPerDay??null,checkins:Array.isArray(r.checkins)?r.checkins.slice(-12):[],questionStats:r.questionStats&&typeof r.questionStats==='object'?r.questionStats:{},weakTopics:Array.isArray(r.weakTopics)?r.weakTopics.slice(-20):[],memoryNotes:Array.isArray(r.memoryNotes)?r.memoryNotes.filter(x=>typeof x==='string').slice(-60):[]};
  const image=typeof body.image==='string'?body.image:null,validImage=image&&/^data:image\/(jpeg|jpg|png|webp|gif);base64,/i.test(image)&&image.length<4500000;if(!messages.length&&!validImage)return res.status(400).json({error:'Please enter a study request or upload a photo.'});if(image&&!validImage)return res.status(400).json({error:'That image could not be accepted. Try a smaller JPG, PNG, or screenshot.'});
  const roles={manager:'Coordinate the study team and give the student the most useful checked response.',researcher:'Keep work aligned with CSEC/CXC scope and question styles.',questionwriter:'Create original practice questions. Hide answers unless asked.',solver:'Solve independently with enough working to verify.',verifier:'Check correctness, ambiguity and grading carefully.',tutor:'Teach step by step in clear student-friendly language.',mistakes:'Identify error patterns and targeted next practice.',planner:'Build realistic study plans from goals and available time.',examiner:'Act like a fair CSEC examiner and give useful feedback.',flashcards:'Create concise active-recall flashcards.',review:'Plan spaced review of weak and older material.',progress:'Summarize progress from supplied evidence only.',goaltracker:'Turn study goals into concrete milestones.',studycoach:'Help choose a manageable next study action.',notes:'Turn material into organized topic notes.',challenge:'Create progressively harder original challenges.',syllabustracker:'Track CSEC syllabus coverage from supplied evidence.',resourcefinder:'Suggest safe relevant study resources without inventing links.'};
  const instructions=`You are the ${agent} role in a coordinated CSEC/CXC Maths study team. ${roles[agent]} Mode: ${mode}. Topic: ${topic}. The student is a teenager, so keep guidance age-appropriate. Do not claim background agents are running. For hint mode, do not reveal the final answer unless asked. For checking work, identify the first meaningful error and explain it. Use the supplied study context only as evidence; never invent progress. CURRENT STUDY CONTEXT: ${JSON.stringify(studyContext)}. Use plain text and clear maths. Return only JSON matching the requested schema. studentUpdate.memoryNotes must contain only new evidence-based durable study facts from this turn, otherwise [].`;
  const apiInput=messages.map(m=>({role:m.role,content:[{type:m.role==='assistant'?'output_text':'input_text',text:m.content}]}));if(validImage){if(!apiInput.length||apiInput.at(-1).role!=='user')apiInput.push({role:'user',content:[{type:'input_text',text:'Please check the study work in this image.'}]});apiInput.at(-1).content.push({type:'input_image',image_url:image,detail:'high'})}
  const schema={type:'object',additionalProperties:false,properties:{answer:{type:'string'},studentUpdate:{type:'object',additionalProperties:false,properties:{memoryNotes:{type:'array',items:{type:'string'}}},required:['memoryNotes']}},required:['answer','studentUpdate']};
  try{const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_TUTOR_MODEL||'gpt-5.4',instructions,input:apiInput,reasoning:{effort:validImage||['manager','verifier','solver'].includes(agent)?'medium':'low'},max_output_tokens:2200,text:{format:{type:'json_schema',name:'study_team_response',strict:true,schema}}})});const data=await response.json();if(!response.ok){console.error('OpenAI error',data);return res.status(response.status).json({error:data?.error?.message||'AI request failed.'})}let raw='';for(const item of data.output||[])for(const part of item.content||[])if(part.type==='output_text'&&typeof part.text==='string')raw+=part.text;if(!raw.trim())return res.status(502).json({error:'The AI returned an empty response.'});let parsed;try{parsed=JSON.parse(raw)}catch{return res.status(502).json({error:'The AI Team response could not be read. Please try again.'})}return res.status(200).json({answer:typeof parsed.answer==='string'?parsed.answer.trim():'',studentUpdate:parsed.studentUpdate||{memoryNotes:[]}})}catch(err){console.error(err);return res.status(500).json({error:'Could not reach the AI service.'})}
}